name: lint

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "**/*.rs"
      - .github/workflows/linter.yml

jobs:
  clippy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: docker://ghcr.io/linkerd/dev:v36-rust
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy

  fmt:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: docker://ghcr.io/linkerd/dev:v36-rust
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --check
